// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkOx4nimTIu7jIU_GqUwsYagCyVIn-0Lw',
    appId: '1:292707401346:web:e59b1f55408f140cd77e9b',
    messagingSenderId: '292707401346',
    projectId: 'qrticketvalidator',
    authDomain: 'qrticketvalidator.firebaseapp.com',
    storageBucket: 'qrticketvalidator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANoVDfuuK_pgV3EcNkfS977SwelB2GpgE',
    appId: '1:292707401346:android:89afaf8c88977340d77e9b',
    messagingSenderId: '292707401346',
    projectId: 'qrticketvalidator',
    storageBucket: 'qrticketvalidator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRxl_AYFtOJBsxTUGCbpmUWxEoM2SHjkg',
    appId: '1:292707401346:ios:283636388a0f7ceed77e9b',
    messagingSenderId: '292707401346',
    projectId: 'qrticketvalidator',
    storageBucket: 'qrticketvalidator.firebasestorage.app',
    iosBundleId: 'com.example.qrapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRxl_AYFtOJBsxTUGCbpmUWxEoM2SHjkg',
    appId: '1:292707401346:ios:283636388a0f7ceed77e9b',
    messagingSenderId: '292707401346',
    projectId: 'qrticketvalidator',
    storageBucket: 'qrticketvalidator.firebasestorage.app',
    iosBundleId: 'com.example.qrapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkOx4nimTIu7jIU_GqUwsYagCyVIn-0Lw',
    appId: '1:292707401346:web:140e79d98304f303d77e9b',
    messagingSenderId: '292707401346',
    projectId: 'qrticketvalidator',
    authDomain: 'qrticketvalidator.firebaseapp.com',
    storageBucket: 'qrticketvalidator.firebasestorage.app',
  );
}
